### ISSUE TITLE
figure out interesting timeline events or other website components

### ISSUE THREAD

**Issue by nathanesau** [nathanesau/ezhacks#3]

**Comment by skylerlll** [comment]
Jan, 2020 -Bushfires in Australia
Jan 9, 2020 -WHO announced COVID

Mar 9, 2020 -Stock market crash
Mar 12, 2020 -Stock market crash
Mar 16, 2020 -Stock market crash

**Comment by skylerlll** [comment]
Oct 2, 2020 -Trump tested positive for COVID

**Comment by nathanesau** [comment]
We don't have time to finish the timeline component. we are scrapping this.
